### PR TITLE
Initial draft to transform existing query functionality to prepared statements.

### PR DESCRIPTION
**Pull request by M4LuZ**
Introduces function qry2stmt that transform LS-style queries (with `%int%`,`%string%`,`%plain%`) to a MySQL prepared statement with bound variables.

There are still some issues as described in #183 so very much WIP with help appreciated

#refs 183

### CODE REVIEW

**Comment by mrflobow** [comment]
I had a look into your transforming function and I think the issue is more in the way the DB class currently works.
You first call a query then the result it's stored in the current instance (maybe sometimes not), sometimes out of the function.

A better approach in my opinion

wrapper function e.g. 

fetch_array($query,...$params)
     -> calls a prepared statement function or simple query function private in the class
     -> returns result set or false

As a additional improvement use this as singleton

DBService::getInstance()->fetch_array("SELECT * FROM xyz WHERE id = ?",$id)
(Depending on PHP version either with ssi.. etc or PHP8 without)

I believe creating a seperate class and migrating exiting might from time to time might be an option.


I suggest some optimizing (if you want to stay with your approach)

````
$query_stmt = str_replace('%string%','?',$query);
        $query_stmt = str_replace('%int%','?',$query_stmt);
        $query_stmt = str_replace('%plain%','?',$query_stmt);

        //due to the usage of %plain% to drop in parts of the SQL statement it is required to iterate through query and deal with each entry separately
        $query_split = preg_split('((%string%|%int%|%plain%))',$query,-1,PREG_SPLIT_DELIM_CAPTURE);
        $query_param=''; //type definition for prepare statement

        foreach ($query_split as $query_element) {
            switch ($query_element) {
                case '%int%': //insert placeholder and write statement element with iterator
                    $query_param .= 'i';
                    break;
                case '%string%': //insert placeholder and write statement element with iterator
                    $query_param .= 's';
                    break;
                case '%plain%': //insert content as-is with iterator
                    $query_param .= 's';
                    break;
            }
        }

$stmt = $this->link_id->prepare($query_stmt);
$stmt->bind_param($query_param,...$args); 
$ok = $stmt->execute();
....


```

**Comment by M4LuZ** [comment]
Hi @mrflobow ,

>  You first call a query then the result it's stored in the current instance (maybe sometimes not), sometimes out of the function.

What do you mean by that?
Also I have some trouble understanding your approach here:
* to me it appears that `fetch_array` would be on the same abstraction level (and apparently even has the same parameters) as `qry` currently.
* The singleton pattern would be just a refactoring without a functional impact (if we store the connection in an object instance globally available or as static class attribute globally available does not make a change in how it works, does it?)
* as per comment in #183 (which I guess refers to something here): The return value of mysqli::get_result() is either a `mysql_result` object or boolean `false` (see https://www.php.net/manual/en/mysqli-stmt.get-result.php)

**Comment by andygrunwald** [comment]
FYI: I rebased this PR against the latest master.

**Comment by andygrunwald** [comment]
I am all in for supporting Prepared Statements and even making this the new default.
I am not really sure if we should try to change the DB-Class with the existing functionality to support Prepared Statements.

From my current gut feeling we would benefit from a new Database class with first-level Prepared Statement support. Also to support unit testing and other functionality from the start. And then migrate query by query. This will take a while, this is correct.
But we would not run into several different (edge) cases like described here.

### PDO vs. mysqli

Another question that comes into my mind: Which Prepared Statement implementation should we use? PDO or mysqli?
LANSuite depends already on mysqli, which makes it easy to implement.
PDO would be a newly required extension (which is part of the standard distribution of nearly every PHP package for every Operating system).

What I like In particular about the PDO-Implementation: Named-Parameters (`:name`), see https://www.php.net/manual/en/pdo.prepare.php

This would make the query easier to read, because you don't have to count the number of `?`.

A good comparison is available here: https://websitebeaver.com/php-pdo-vs-mysqli

I would like to get your opinion on this, before we move on.

**Comment by andygrunwald** [comment]
See https://github.com/lansuite/lansuite/pull/641 as an additional proposal.

**Comment by M4LuZ** [comment]
Closing this as most of it it has been made obsolete with PRs #641 and #662.
It should now be very easy to create a wrapper from DB to Database that also includes mapping of the query calls.
But it makes sense to start there with a fresh codebase instead of continuing here

**Pull request closed without merging**
