### PR TITLE
Module "equipment": Delete module equipment, because http://www.orgapage.net/ is not available anymore

### PR DESCRIPTION
**Pull request by andygrunwald**
This PR deletes the complete `equipment` module.
This module was responsible to integrate an OrgaPage-Shop into LanSuite.

http://www.orgapage.net/ doesn't exist anymore. This module is not functional anymore.

### CODE REVIEW

**Comment by andygrunwald** [comment]
@M4LuZ Am I free to merge here? Anything that would block this PR?

**Comment by M4LuZ** [comment]
I'm fine with this, just thought that you also wanted feedback from @JochenJung

**Comment by JochenJung** [comment]
Fine with me :-)

**Comment by andygrunwald** [comment]
👍

**Pull request merged**
