### PR TITLE
Make PHP syntax check fatal

### PR DESCRIPTION
**Pull request by lxp**

### CODE REVIEW

**Comment by lxp** [comment]
Okay, syntax check on nightly is failing.
I am going to add an exception for it.

**Comment by andygrunwald** [comment]
This should catch the heavy errors.

**Comment by lxp** [comment]
Yeah, I think so too.
Maybe we should just remove the ext_scripts/gd stuff in the long term, then we might also be able to re-enable fatal checks for nightly.
But I think we should first try to fix code style and make code style checks fatal.

**Comment by andygrunwald** [comment]
Agree here.

**Pull request merged**
