### PR TITLE
Fix #232: Upgrade fpdf to v1.8.1

### LINKED ISSUE #232: Module "pdf": Upgrade fpdf and include it as composer dependency
## Context

In the PDF Module we use external code  (fpdf in version 1.52).
fpdf itself is available as composer dependency in version v1.8.1
See https://packagist.org/packages/setasign/fpdf

## Expected Behavior

Upgrade fpdf to v1.8.1 and include this as composer dependency.

## Your Environment

* Version used: Current master (rev c1b2c82)
* Enabled features: pdf-module

### PR DESCRIPTION
**Pull request by andygrunwald**
This is a follow up of #233.

**Attention**: Don't merge this before #233. This branch depends on #233.

This PR:
- Updates fpdf to v1.8.1
- Adds fpdf as composer dependency

This PR has one disadvantage:
In the current LanSuite version, all fonts are stored in `ext_inc/pdf_fonts/`. The `ext_inc/` folder is used to store external / user data. During an update, this folder should not be touched.
In the folder `ext_inc/pdf_fonts/` you can add your custom fonts via fpdf (see [Adding new fonts and encodings](http://www.fpdf.org/en/tutorial/tuto7.htm).
The format of fonts has changed. This means that the fonts stored in `ext_inc/pdf_fonts/` can't be used anymore.
Users who added custom fonts are not able to use those anymore, because we dropped the custom font path.

My recommendation:
We document this in the upgrade path document. We write that users should drop the content of the `ext_inc/pdf_fonts/` folder and recreate their custom fonts and add them to `ext_inc/pdf_fonts/`.
With this only custom, fonts are stored in `ext_inc/pdf_fonts/`.
Native fonts are stored in vendor-folder.

@M4LuZ If you agree with this, I would continue and implement this feature for custom fonts in this PR.

Related issue: #232

### CODE REVIEW

**Comment by M4LuZ** [comment]
> The format of fonts has changed. This means that the fonts stored in ext_inc/pdf_fonts/ can't be used anymore.
Users who added custom fonts are not able to use those anymore, because we dropped the custom font path.

Sorry, but is this now incompatible just because of the path or because the fonts themselves became incompatible?

**Comment by andygrunwald** [comment]
> [...] because the fonts themselves became incompatible

This.
See e.g. the font *helvetica.php*:

- [Current helvetica.php in LanSuite](https://github.com/lansuite/lansuite/blob/master/ext_inc/pdf_fonts/helvetica.php)
- [New helvetica.php in fpdf](https://github.com/Setasign/FPDF/blob/master/font/helvetica.php)

As you see in the new version tons of more information are stored per font. According to my tests, that information is necessary to render the new font.

The thing is: The `ext_inc` folder is used to store user information. And in my opinion we should treat it like this, because this makes updates much easier for us and the user.
Because of this we 

a) need to change the font path or
b) need to explain this to every user and edit files manually there

Is this now more clear?

**Comment by M4LuZ** [comment]
>The thing is: The ext_inc folder is used to store user information.

Not just that, but anything that is no source-code. Not necessarily user-related.
So I would just leave the `define('FPDF_FONTPATH', 'ext_inc/pdf_fonts/');`in.
Regarding incompatible font files:
A warning in the upgrade guide would be the minimal requirement.
If we get an upgrade function up and running (see mockup in #90), we could just check the folder for content and warn if any fonts are found there.

**Comment by andygrunwald** [comment]
> Not just that, but anything that is no source-code. Not necessarily user-related.

The font-definition are PHP files and those are source code.
So they should not stay in `ext_inc`.

Related to the update, i added this to https://github.com/lansuite/lansuite/issues/214

**Pull request merged**
