### PR TITLE
Issue #68: Drop pre generated docs/ folder, because we are able to generate those for every release

### PR DESCRIPTION
**Pull request by andygrunwald**
See #68 for detail reasons.

### CODE REVIEW

**Comment by M4LuZ** [comment]
Wouldn't it make sense to have  at least a note somewhere how to re-create the docs ready first?
Or did I just miss that?

**Comment by andygrunwald** [comment]
@M4LuZ Right. This make sense :)

I added a note to the README on how to generate the HTML Version of the API.
PDF and CHM is not possible anymore, because my example is using the [phpDocumentor](https://www.phpdoc.org/) in Version 2.

Does this fit for you? If yes, feel free to merge it!

**Comment by andygrunwald** [comment]
Any update here @M4LuZ ?

@jannaahs What is your opinion?

**Comment by jannaahs** [comment]
I am fine with the note in the README.

**Comment by M4LuZ** [comment]
Hi,

fine by me.
Regarding PDF and CHM:
Former would be good, I don't think we need the later.
But I'm quite sure that phpDocumentor is able to export to PDF.
Even if not, I think the syntax is also parseable by Doxygen, so that shouldn't be an issue either way

**Pull request merged**
