### PR TITLE
Docker-Environment for LanSuite

### PR DESCRIPTION
**Pull request by andygrunwald**
This PR offers a complete [Docker](https://www.docker.com/) Docker setup and offers people to just start and try out Lansuite.
Further more engineers can use this for development in a isolated environment and they can easily play around with others version of PHP, Extensions or MySQL.

### CODE REVIEW

**Comment by jannaahs** [comment]
I tried to run with docker and followed you instructions in the README.

I got the following error:
```
Jan@DESKTOP /d/xampp/htdocs/lansuite (docker-compose)
$ docker-compose up
Pulling php (lansuite/lansuite:latest)...
repository lansuite/lansuite not found: does not exist or no pull access
```

**Comment by andygrunwald** [comment]
Ah. true. Forget to push it. Will take care. Can take a few hours, because i an on the road with flaky internet. Will ping you @jannaahs

**Comment by andygrunwald** [comment]
@jannaahs Try again please.
I pushed the image to Dockerhub (see https://hub.docker.com/r/lansuite/lansuite/).
Once this is merged, i will setup the automated building process via Webhooks that we don't have to take care about it anymore :)

**Comment by jannaahs** [comment]
First error (known error on Windows):
```
Jan@DESKTOP /d/xampp/htdocs/lansuite (docker-compose)
$ docker-compose up
client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
```
Solution: set ```version``` in ```docker-compose.yml``` from 2 to 2.1


Second error:
```
Jan@DESKTOP /d/xampp/htdocs/lansuite (docker-compose)
$ docker-compose up
Creating network "lansuite_code-network" with driver "bridge"
plugin not found
```

**Comment by jannaahs** [comment]
Using Linux Container:
```
Jan@DESKTOP /d/xampp/htdocs/lansuite (docker-compose)
$ docker-compose up
Starting lansuite_mysql_1
Creating lansuite_php_1
Creating lansuite_web_1

ERROR: for web  Cannot create container for service web: D: drive is not shared. Please share it in Docker for Windows Settings

ERROR: for php  Cannot create container for service php: D: drive is not shared. Please share it in Docker for Windows Settings
Encountered errors while bringing up the project.
```

**Comment by andygrunwald** [comment]
Thanks @jannaahs for testing.
I raised the `docker-compose` to version 3. According to the documentation [Compose file versions and upgrading](https://docs.docker.com/compose/compose-file/compose-versioning/) this is the most current used and recommended one.

About the volume error: Are you running Windows 10 and Docker for Windows? If yes, checkout https://github.com/docker/for-win/issues/77. Maybe this helps for you?
If not: can you provide more details about
- Your OS + Version
- `docker-compose version`
- `docker --version`
- `docker-machine version` (if you are using docker-machine)

**Pull request merged**
