### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by t-h-e**
upgrade base image to php 7.4.11
as well as necessary dependencies
to be able to create a docker image for lansuite again

### CODE REVIEW

**Comment by andygrunwald** [comment]
Hey @t-h-e,
thanks a lot for this pull request.
The changes are looking good and I would love to merge this. However, jumping from PHP 7.0 to PHP 7.4 might not be as straightforward.
Especially in LanSuite, this source is quite old and I am not 100% sure if it runs as expected on PHP 7.4.
That is the reason why I am not hitting the merge button immediately.

@M4LuZ What do you think?

**Comment by t-h-e** [comment]
No worries. I should have mentioned that I have not tested it further than just checking if the lansuit setup starts.
I'm trying to migrate from a rather old lansuite version with a few minor changes to the current version. While also migrating the changes. If the changes still seem useful, I will create pull requests for them.
Anyway I will have to test everything after migrating anyway, so for me it's also fine to leave the pull request here until further confirmation that lansuite works properly with php 7.4
At least here the change is already accessible to everyone 😃

**Comment by M4LuZ** [comment]
I would propose to change dockerfile to PHP 7.2 at first (as that is fairly certain to work) and upgrade travis to build against 7.2 -7.4.
If we don't get any complaints from there we should give 7.4 a shot and update version then

**Comment by t-h-e** [comment]
7.2 is fine for me as well for now, but keep in mind that 7.2 is nearly end of life as well.
see https://www.php.net/supported-versions.php

**Comment by M4LuZ** [comment]
That is well known and understood. 
Reason why I specifically mention PHP 7.2 is because that is the highest version we test against in Travis and thus had at least some test coverage by the CI-System. 
I agree that we should move on to 7.4 ASAP and only see that as stop-gap measure till then.

**Review by M4LuZ — APPROVED** [review]

**Pull request merged**
